version: 2

models:
  - name: dim_companies
    description: "Dimension table combining ABR entity details and commoncrawl presence"
    columns:
      - name: abn
        description: "ABN number"
        tests:
          - not_null
      - name: entity_name
        description: "Business name from ABR"
        tests:
          - not_null
      - name: url
        description: "Matched URL from commoncrawl"
        tests:
          - not_null

  - name: fact_company_presence
    description: "Fact table tracking matched companies and web presence"
    columns:
      - name: abn
        description: "ABN from ABR source"
        tests:
          - not_null
      - name: url
        description: "Web URL from commoncrawl"
        tests:
          - not_null
      - name: industry
        description: "Industry classification"
        tests: []

  - name: dim_companies_likely
    description: "Dimension table using fuzzy matching between ABR and CommonCrawl"
    columns:
      - name: abn
        description: "ABN number from ABR"
      - name: entity_name
        description: "Entity name from ABR"
      - name: company_name
        description: "Company name from CommonCrawl"
      - name: url
        description: "Matched URL"
      - name: name_distance
        description: "Levenshtein distance between entity and company names"
